name: your_project_name  # Replace with your project name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Other dependencies can be added here

flutter:
  uses-material-design: true
  assets:
    - assets/images/africa 1.png
    - assets/images/asia-512 1.png
    - assets/images/australia 1.png
    - assets/images/img.png
    - assets/images/africa 1.png
    - assets/images/asia-512 2.png

    - assets/secondpage/Australia.png
    - assets/secondpage/canada.png
    -  assets/secondpage/cuba.png
    - assets/secondpage/Greenland.png
    - assets/secondpage/india.png
    - assets/secondpage/jamaica.png
    - assets/secondpage/maxico.png
    - assets/secondpage/Usa.png



    -  assets/thirdpage/AdTech.jpg
    -  assets/thirdpage/Advanced_Manufacturing.png
    -  assets/thirdpage/AgTech.png
    -  assets/thirdpage/AI:ML.png
    -  assets/thirdpage/AiGenerated.png
    -  assets/thirdpage/Audio_Tech.png
    -  assets/thirdpage/Augmented_Reality.png